version: '3.9'

networks:
  payments-tests:
    driver: bridge

services:
  payments_test:
    container_name: payments_api
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.test
    volumes:
      - $PWD:/go/src/github.com/tamasbrandstadter/payments-api
    depends_on:
      - db
      - mq
      - redis
    networks:
      - payments-tests
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    command: redis-server --requirepass securepass
    ports:
      - 6379:6379
    networks:
      - payments-tests
  mq:
    image: rabbitmq:3.8.14-management
    container_name: mq
    hostname: mq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - payments-tests
  db:
    image: postgres:latest
    hostname: db
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    restart: on-failure
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - payments-tests
