kind: ServiceAccount
apiVersion: v1
metadata:
  name: payments-api
  namespace: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api-deployment
  namespace: payments
  labels:
    app: payments-api
spec:
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 2
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      serviceAccountName: payments-api
      terminationGracePeriodSeconds: 30
      containers:
        - name: payments-api
          image: payments-api:1.0.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 150m
              memory: 200Mi
            limits:
              memory: 200Mi
          env:
            - name: DB_HOST
              value: postgres.payments.svc.cluster.local
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: postgres-secret
            - name: DB_PORT
              value: "5432"
            - name: MQ_HOST
              value: rabbitmqcluster.payments.svc.cluster.local
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: rabbit-secret
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  key: USER
                  name: rabbit-secret
            - name: MQ_PORT
              value: "5672"
            - name: CACHE_HOST
              value: redis-master.payments.svc.cluster.local
            - name: CACHE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: redis-secret
            - name: CACHE_PORT
              value: "6379"
