apiVersion: v1
kind: Service
metadata:
  name: payments-api
  namespace: payments
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/instance: payments-api
spec:
  selector:
    app: payments-api
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
