apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  namespace: payments
  name: rabbitmqcluster
spec:
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 1700
      default_user= guest
      default_pass = guest
      default_user_tags.administrator = true
  service:
    type: LoadBalancer